obj-$(CONFIG_TOUCHSCREEN_ILI)	+=  ilitek_hostdl.o
obj-$(CONFIG_TOUCHSCREEN_ILI)	+=  ilitek_ic.o
obj-$(CONFIG_TOUCHSCREEN_ILI)	+=  ilitek_main.o
obj-$(CONFIG_TOUCHSCREEN_ILI)	+=  ilitek_mp.o
obj-$(CONFIG_TOUCHSCREEN_ILI)	+=  ilitek_node.o
obj-$(CONFIG_TOUCHSCREEN_ILI)   +=  ilitek_plat_qcom.o
obj-$(CONFIG_TOUCHSCREEN_ILI)   +=  ilitek_spi.o
obj-$(CONFIG_TOUCHSCREEN_ILI)	+=  ilitek_touch.o
